# Generated by Django 2.1.5 on 2019-01-19 14:52

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobspage_postpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='intro',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
