# Generated by Django 2.1.5 on 2019-01-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('jobs', '0004_formpage_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobspage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='postpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='JobsPage',
        ),
        migrations.DeleteModel(
            name='PostPage',
        ),
    ]
