# Generated by Django 2.1.5 on 2019-01-19 16:01

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20190119_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_fields', to='jobs.FormPage'),
        ),
    ]
